using System;
using System.Collections.Generic;

namespace APIWiltelSoftland.Entities
{
    public partial class Cvmcth
    {
        public string CvmcthCodemp { get; set; }
        public string CvmcthCodcon { get; set; }
        public string CvmcthNrocon { get; set; }
        public short CvmcthNroext { get; set; }
        public string CvmcthDescrp { get; set; }
        public string CvmcthNrocta { get; set; }
        public string CvmcthNrosub { get; set; }
        public string CvmcthCndpag { get; set; }
        public string CvmcthVnddor { get; set; }
        public string CvmcthCodctr { get; set; }
        public string CvmcthModcvt { get; set; }
        public string CvmcthCodcvt { get; set; }
        public string CvmcthModcst { get; set; }
        public string CvmcthCodcst { get; set; }
        public string CvmcthDeposi { get; set; }
        public string CvmcthSector { get; set; }
        public DateTime? CvmcthFchmov { get; set; }
        public string CvmcthActcof { get; set; }
        public DateTime? CvmcthFacdes { get; set; }
        public DateTime? CvmcthFachas { get; set; }
        public DateTime? CvmcthPrifac { get; set; }
        public DateTime? CvmcthUltfac { get; set; }
        public DateTime? CvmcthUfaaux { get; set; }
        public short? CvmcthFreact { get; set; }
        public short? CvmcthFrefac { get; set; }
        public DateTime? CvmcthFchaju { get; set; }
        public DateTime? CvmcthFchula { get; set; }
        public DateTime? CvmcthPriact { get; set; }
        public DateTime? CvmcthUltaju { get; set; }
        public DateTime? CvmcthUltbas { get; set; }
        public DateTime? CvmcthFchpeb { get; set; }
        public DateTime? CvmcthFchper { get; set; }
        public DateTime? CvmcthFchteb { get; set; }
        public DateTime? CvmcthFchter { get; set; }
        public DateTime? CvmcthFchbas { get; set; }
        public string CvmcthCodlis { get; set; }
        public string CvmcthGrubon { get; set; }
        public DateTime? CvmcthFeclis { get; set; }
        public string CvmcthCoflis { get; set; }
        public string CvmcthCoffac { get; set; }
        public string CvmcthCofdev { get; set; }
        public string CvmcthActlis { get; set; }
        public string CvmcthTextos { get; set; }
        public string CvmcthDimobl { get; set; }
        public string CvmcthSubcue { get; set; }
        public string CvmcthDimori { get; set; }
        public string CvmcthSubori { get; set; }
        public string CvmcthCoef01 { get; set; }
        public string CvmcthCoef02 { get; set; }
        public string CvmcthCoef03 { get; set; }
        public string CvmcthCoef04 { get; set; }
        public string CvmcthCoef05 { get; set; }
        public decimal? CvmcthPctc01 { get; set; }
        public decimal? CvmcthPctc02 { get; set; }
        public decimal? CvmcthPctc03 { get; set; }
        public decimal? CvmcthPctc04 { get; set; }
        public decimal? CvmcthPctc05 { get; set; }
        public string CvmcthUnific { get; set; }
        public decimal? CvmcthCoefic { get; set; }
        public string CvmcthRubr01 { get; set; }
        public string CvmcthRubr02 { get; set; }
        public string CvmcthRubr03 { get; set; }
        public string CvmcthRubr04 { get; set; }
        public string CvmcthRubr05 { get; set; }
        public string CvmcthRubr06 { get; set; }
        public string CvmcthRubr07 { get; set; }
        public string CvmcthRubr08 { get; set; }
        public string CvmcthRubr09 { get; set; }
        public string CvmcthRubr10 { get; set; }
        public string CvmcthVtcero { get; set; }
        public string CvmcthOleole { get; set; }
        public string CvmcthEstcon { get; set; }
        public string CvmcthEstact { get; set; }
        public string CvmcthObshis { get; set; }
        public string CvmcthPercan { get; set; }
        public string CvmcthRecnov { get; set; }
        public DateTime? CvmcthFchrte { get; set; }
        public DateTime? CvmcthUltfba { get; set; }
        public DateTime? CvmcthFchinb { get; set; }
        public DateTime? CvmcthPriaju { get; set; }
        public DateTime? CvmcthAuxrte { get; set; }
        public DateTime? CvmcthAuxfba { get; set; }
        public DateTime? CvmcthAuxaju { get; set; }
        public string CvmcthCerdec { get; set; }
        public string CvmcthTipopr { get; set; }
        public string CvmcthCodopr { get; set; }
        public string CvmcthTipexp { get; set; }
        public string CvmcthCndcom { get; set; }
        public string UsrCvmcthCodtec { get; set; }
        public int? UsrCvmcthCodenl { get; set; }
        public string UsrCvmcthCodpro { get; set; }
        public string UsrCvmcthDirecc { get; set; }
        public string UsrCvmcthNumero { get; set; }
        public string UsrCvmcthDppiso { get; set; }
        public string UsrCvmcthDeptos { get; set; }
        public string UsrCvmcthNombre { get; set; }
        public string UsrCvmcthCodpos { get; set; }
        public string UsrCvmcthCodpai { get; set; }
        public string UsrCvmcthCodext { get; set; }
        public short? UsrCvmcthNcarte { get; set; }
        public string UsrCvmcthUnific { get; set; }
        public string UsrCvmcthMascar { get; set; }
        public string UsrCvmcthNrotar { get; set; }
        public string UsrCvmcthModifi { get; set; }
        public DateTime? UsrCvmcthFcfinot{ get; set; }
        public DateTime? CvmcthFecalt { get; set; }
        public DateTime? CvmcthFecmod { get; set; }
        public string CvmcthUserid { get; set; }
        public string CvmcthUltopr { get; set; }
        public string CvmcthDebaja { get; set; }
        public string CvmcthOalias { get; set; }
    }
}
