using System;
using System.Collections.Generic;

namespace APIWiltelSoftland.Entities
{
    public partial class Vtrmvh
    {
        public string VtrmvhCodemp { get; set; }
        public string VtrmvhModfor { get; set; }
        public string VtrmvhCodfor { get; set; }
        public int VtrmvhNrofor { get; set; }
        public string VtrmvhModcom { get; set; }
        public string VtrmvhCodcom { get; set; }
        public string VtrmvhSucurs { get; set; }
        public int? VtrmvhHstfor { get; set; }
        public string VtrmvhTextos { get; set; }
        public DateTime VtrmvhFchmov { get; set; }
        public string VtrmvhNrocta { get; set; }
        public string VtrmvhNrosub { get; set; }
        public string VtrmvhImptcn { get; set; }
        public string VtrmvhCodlis { get; set; }
        public string VtrmvhCndpag { get; set; }
        public string VtrmvhVnddor { get; set; }
        public string VtrmvhEmpasi { get; set; }
        public string VtrmvhModasi { get; set; }
        public string VtrmvhCodasi { get; set; }
        public int? VtrmvhNroasi { get; set; }
        public string VtrmvhGrubon { get; set; }
        public short? VtrmvhImpres { get; set; }
        public string VtrmvhCoflis { get; set; }
        public string VtrmvhCobrad { get; set; }
        public decimal? VtrmvhCambio { get; set; }
        public string VtrmvhCoffac { get; set; }
        public string VtrmvhCofdeu { get; set; }
        public string VtrmvhDimobl { get; set; }
        public string VtrmvhSubcue { get; set; }
        public string VtrmvhDimori { get; set; }
        public string VtrmvhSubori { get; set; }
        public string VtrmvhDimuni { get; set; }
        public string VtrmvhJurisd { get; set; }
        public string VtrmvhCodzon { get; set; }
        public string VtrmvhEmprev { get; set; }
        public string VtrmvhModrev { get; set; }
        public string VtrmvhCodrev { get; set; }
        public int? VtrmvhNrorev { get; set; }
        public decimal? VtrmvhCamuss { get; set; }
        public string VtrmvhCndiva { get; set; }
        public int? VtrmvhLotein { get; set; }
        public string VtrmvhDesmov { get; set; }
        public DateTime? VtrmvhFchven { get; set; }
        public string VtrmvhEmpfcr { get; set; }
        public string VtrmvhModfcr { get; set; }
        public string VtrmvhCodfcr { get; set; }
        public int? VtrmvhNrofcr { get; set; }
        public DateTime? VtrmvhFecfcr { get; set; }
        public short? VtrmvhStafcr { get; set; }
        public string VtrmvhEmprim { get; set; }
        public string VtrmvhModrim { get; set; }
        public string VtrmvhCodrim { get; set; }
        public int? VtrmvhNrorim { get; set; }
        public string VtrmvhEmpdcr { get; set; }
        public string VtrmvhModdcr { get; set; }
        public string VtrmvhCoddcr { get; set; }
        public int? VtrmvhNrodcr { get; set; }
        public decimal? VtrmvhCamsec { get; set; }
        public string VtrmvhTipopr { get; set; }
        public string VtrmvhCodopr { get; set; }
        public string VtrmvhCodope { get; set; }
        public int? VtrmvhCodori { get; set; }
        public short? VtrmvhEstaut { get; set; }
        public string VtrmvhUsraut { get; set; }
        public DateTime? VtrmvhFchaut { get; set; }
        public string VtrmvhOricom { get; set; }
        public string VtrmvhOricod { get; set; }
        public string VtrmvhNrocae { get; set; }
        public DateTime? VtrmvhVencae { get; set; }
        public int? VtrmvhNidcae { get; set; }
        public string VtrmvhDocfis { get; set; }
        public string VtrmvhLetfis { get; set; }
        public string VtrmvhSucfis { get; set; }
        public int? VtrmvhNrofis { get; set; }
        public DateTime? VtrmvhFchpar { get; set; }
        public string VtrmvhUtpaor { get; set; }
        public int? VtrmvhNidfex { get; set; }
        public int? VtrmvhIdtfex { get; set; }
        public string VtrmvhCndcom { get; set; }
        public string VtrmvhTipexp { get; set; }
        public DateTime? VtrmvhFchfce { get; set; }
        public string VtrmvhCodsce { get; set; }
        public string VtrmvhClamov { get; set; }
        public int? VtrmvhClaaut { get; set; }
        public string UsrVtrmvhMarcaea { get; set; }
        public short? UsrVtrmvhSubftp { get; set; }
        public string UsrVtrmvhEnviogl { get; set; }
        public string UsrVtrmvhEnvmai { get; set; }
        public string UsrVtrmvhImagen { get; set; }
        public int? UsrVtrmvhIdc { get; set; }
        public string UsrVtrmvhCodbar { get; set; }
        public string UsrVtrmvhCodlnk { get; set; }
        public DateTime? UsrVtrmvhPagows { get; set; }
        public string UsrVtrmvhGencor { get; set; }
        public string UsrVtrmvhArclnk { get; set; }
        public string UsrVtrmvhBrfile { get; set; }
        public string UsrVtrmvhArcbnl { get; set; }
        public string UsrVtrmvhArcbas { get; set; }
        public string UsrVtrmvhArccob { get; set; }
        public string UsrVtrmvhMunicp { get; set; }
        public DateTime? UsrVtrmvhFhsftp { get; set; }
        public string UsrVtrmvhComisi { get; set; }
        public string UsrVtrmvhMedpag { get; set; }
        public string UsrVtrmvhTarjet { get; set; }
        public string UsrVtrmvhNrotar { get; set; }
        public string UsrVtrmvhBanco { get; set; }
        public string UsrVtrmvhNrocbu { get; set; }
        public string UsrVtrmvhIdfact { get; set; }
        public string UsrVtrmvhGennov { get; set; }
        public string UsrVtrmvhSocio { get; set; }
        public string UsrVtrmvhCodboc { get; set; }
        public string UsrVtrmvhCodter { get; set; }
        public short? UsrVtrmvhCodent { get; set; }
        public string UsrVtrmvhEntdeb { get; set; }
        public DateTime? VtrmvhFecalt { get; set; }
        public DateTime? VtrmvhFecmod { get; set; }
        public string VtrmvhUserid { get; set; }
        public string VtrmvhUltopr { get; set; }
        public string VtrmvhDebaja { get; set; }
        public string VtrmvhOalias { get; set; }
    }
}
