using System;
using System.Collections.Generic;

namespace APIWiltelSoftland.Entities
{
    public partial class Vtrmvi
    {
        public string VtrmviCodemp { get; set; }
        public string VtrmviModfor { get; set; }
        public string VtrmviCodfor { get; set; }
        public int VtrmviNrofor { get; set; }
        public int VtrmviNroitm { get; set; }
        public string VtrmviDebhab { get; set; }
        public string VtrmviModcpt { get; set; }
        public string VtrmviTipcpt { get; set; }
        public string VtrmviCodcpt { get; set; }
        public string VtrmviCuenta { get; set; }
        public decimal? VtrmviCantid { get; set; }
        public decimal? VtrmviFactor { get; set; }
        public string VtrmviUnimed { get; set; }
        public string VtrmviTipuni { get; set; }
        public string VtrmviUnifac { get; set; }
        public decimal? VtrmviFacfac { get; set; }
        public decimal? VtrmviCntfac { get; set; }
        public string VtrmviUnialt { get; set; }
        public decimal? VtrmviFacalt { get; set; }
        public decimal? VtrmviCntalt { get; set; }
        public string VtrmviUnicon { get; set; }
        public decimal? VtrmviFaccon { get; set; }
        public decimal? VtrmviCntcon { get; set; }
        public decimal? VtrmviOldpre { get; set; }
        public decimal? VtrmviNewpre { get; set; }
        public decimal? VtrmviPrenac { get; set; }
        public decimal? VtrmviImpnac { get; set; }
        public decimal? VtrmviPreuss { get; set; }
        public decimal? VtrmviImpuss { get; set; }
        public decimal? VtrmviPreext { get; set; }
        public decimal? VtrmviImpext { get; set; }
        public decimal? VtrmviPcinac { get; set; }
        public decimal? VtrmviIcinac { get; set; }
        public decimal? VtrmviPciext { get; set; }
        public decimal? VtrmviIciext { get; set; }
        public decimal? VtrmviPciuss { get; set; }
        public decimal? VtrmviIciuss { get; set; }
        public decimal? VtrmviImpdeb { get; set; }
        public decimal? VtrmviImphab { get; set; }
        public string VtrmviEmpapl { get; set; }
        public string VtrmviModapl { get; set; }
        public string VtrmviCodapl { get; set; }
        public int? VtrmviNroapl { get; set; }
        public short? VtrmviCuoapl { get; set; }
        public string VtrmviTextos { get; set; }
        public string VtrmviTippro { get; set; }
        public string VtrmviArtcod { get; set; }
        public string VtrmviTipdes { get; set; }
        public string VtrmviArtdes { get; set; }
        public string VtrmviNserie { get; set; }
        public string VtrmviNdespa { get; set; }
        public string VtrmviEnvase { get; set; }
        public string VtrmviNotros { get; set; }
        public string VtrmviTserie { get; set; }
        public string VtrmviTdespa { get; set; }
        public string VtrmviTenvas { get; set; }
        public string VtrmviTotros { get; set; }
        public string VtrmviDeposi { get; set; }
        public string VtrmviSector { get; set; }
        public string VtrmviEmpori { get; set; }
        public string VtrmviModori { get; set; }
        public string VtrmviCodori { get; set; }
        public int? VtrmviNroori { get; set; }
        public int? VtrmviItmori { get; set; }
        public string VtrmviExpori { get; set; }
        public decimal? VtrmviPctbf1 { get; set; }
        public decimal? VtrmviPctbf2 { get; set; }
        public decimal? VtrmviPctbf3 { get; set; }
        public decimal? VtrmviPctbf4 { get; set; }
        public decimal? VtrmviPctbf5 { get; set; }
        public decimal? VtrmviPctbf6 { get; set; }
        public decimal? VtrmviPctbf7 { get; set; }
        public decimal? VtrmviPctbf8 { get; set; }
        public decimal? VtrmviPctbf9 { get; set; }
        public decimal? VtrmviPctbfn { get; set; }
        public decimal? VtrmviUssdeb { get; set; }
        public decimal? VtrmviUsshab { get; set; }
        public decimal? VtrmviExtdeb { get; set; }
        public decimal? VtrmviExthab { get; set; }
        public string VtrmviEmpcon { get; set; }
        public string VtrmviCodcon { get; set; }
        public string VtrmviNrocon { get; set; }
        public short? VtrmviNroext { get; set; }
        public int? VtrmviItmcon { get; set; }
        public decimal? VtrmviImpori { get; set; }
        public string VtrmviNfecha { get; set; }
        public string VtrmviNatrib { get; set; }
        public string VtrmviNubica { get; set; }
        public string VtrmviNestan { get; set; }
        public string VtrmviTfecha { get; set; }
        public string VtrmviTatrib { get; set; }
        public string VtrmviTubica { get; set; }
        public string VtrmviTestan { get; set; }
        public string VtrmviClamov { get; set; }
        public decimal? VtrmviImpsec { get; set; }
        public decimal? VtrmviSecdeb { get; set; }
        public decimal? VtrmviSechab { get; set; }
        public string VtrmviTipopr { get; set; }
        public string VtrmviCodopr { get; set; }
        public decimal? VtrmviTasa01 { get; set; }
        public decimal? VtrmviTasa02 { get; set; }
        public decimal? VtrmviTasa03 { get; set; }
        public decimal? VtrmviTasa04 { get; set; }
        public decimal? VtrmviTasa05 { get; set; }
        public decimal? VtrmviTasa06 { get; set; }
        public decimal? VtrmviImpu01 { get; set; }
        public decimal? VtrmviImpu02 { get; set; }
        public decimal? VtrmviImpu03 { get; set; }
        public decimal? VtrmviImpu04 { get; set; }
        public decimal? VtrmviImpu05 { get; set; }
        public decimal? VtrmviImpu06 { get; set; }
        public short? VtrmviAnovig { get; set; }
        public string VtrmviCodcur { get; set; }
        public string VtrmviCodniv { get; set; }
        public string VtrmviCodano { get; set; }
        public decimal? VtrmviIntnoi { get; set; }
        public string VtrmviCodpro { get; set; }
        public string VtrmviDespro { get; set; }
        public DateTime? VtrmviFecalt { get; set; }
        public DateTime? VtrmviFecmod { get; set; }
        public string VtrmviUserid { get; set; }
        public string VtrmviUltopr { get; set; }
        public string VtrmviDebaja { get; set; }
        public string VtrmviOalias { get; set; }
    }
}
